services:
  - type: web
    name: caswen-image-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_service:app --bind 0.0.0.0:$PORT
    plan: free
